### ISSUE TITLE
Custom Domain Support

### ISSUE THREAD

**Issue by gitizenme** [auth0/auth0-oidc-client-net#12]
Hello,

I've configured a custom domain per the docs here: https://auth0.com/docs/custom-domains

When the app navigates to the auth page, the following message appears:

![img_b8615106fab4-1](https://user-images.githubusercontent.com/643504/40684891-82c17958-6347-11e8-99cb-0e02003a0fc9.jpeg)

Domain configuration tests out okay...
![image](https://user-images.githubusercontent.com/643504/40684949-b55aa1dc-6347-11e8-837a-1334dca6f734.png)

Does the OIDC client support custom domains?

**Comment by jerriep** [comment]
Can you post your code here?

**Comment by jerriep** [comment]
@gitizenme Can you also perhaps try and reach out to Auth0 support directly? They are in a much better position than me to assist you with this as they have direct access to the product teams. There is also a better chance that they have encountered this before and may have an answer ready for you.

I am just a freelance contractor, so I do not have the access they do. If there is an actual issue which I need to solve, they can reach out to me. 

I will close this for now. Let me know if you don't have success with support.
