### ISSUE TITLE
Able to log into account but the next statement after authentication is not called. 

### ISSUE THREAD

**Issue by asusralis** [auth0/auth0-oidc-client-net#120]
I was able to log into my account and it navigated back to my app, but nothing is called after it. 

```
_auth0Client = new Auth0Client(new Auth0ClientOptions
            {
                Domain = Auth0Config.Domain,
                ClientId = Auth0Config.ClientId
            });
```
```
public async Task<Auth0AuthenticationResult> Authenticate()
        {
            var result = await _auth0Client.LoginAsync(new { audience = Auth0Config.Audience });

            return BuildResult(result);
        }

```

```
var result = await authService.Authenticate();

// Is never hit
[breakpoint] if (!result.IsError)
                {

                }
```
Xamarin.Forms: 4.3.0.947036
Auth0.OidcClient.Android: 2.4.3 (having problems with 3.0, see other issue)
Auth0.Core: 6.5.4

**Comment by damieng** [comment]
This is normally a case where the redirect URL you are using does not match what the app is setup for.

The step at https://auth0.com/docs/quickstart/native/xamarin/01-login explain how the IntentFilter should be configured so it is called back correctly.

**Comment by asusralis** [comment]
From what I can tell my intent is set up correctly - it had the same directions as the other guide I was following.

```
[IntentFilter(
    new[] { Intent.ActionView },
    Categories = new[] { Intent.CategoryDefault, Intent.CategoryBrowsable },
    DataScheme = "com.saltstudios.deliciousdetails", // App package name
    DataHost = "delicious-details.auth0.com", // Auth0 domain
    DataPathPrefix = "/android/com.saltstudios.deliciousdetails/callback")]
```

Would there be any other place where I could have set something wrong?

**Comment by damieng** [comment]
Are you inheriting your Activity from Auth0ClientActivity ?

**Comment by asusralis** [comment]
Oh, I am not, but it seemed to work. Should I be doing that?

**Comment by damieng** [comment]
You can either inherit from Auth0ClientActivity base or manually dispatch the messages from the OnResume and OnNewIntent (which is all this base class does). 

The quickstart should really be recommending to inherit from Auth0ClientActivity but right now it instead says how to manually dispatch the OnNewIntent - I've no idea why it's missing the OnResume dispatch.

I'll get the quickstart fixed up and aligned with 3.x in the next few days - thanks for bringing that to my attention.
