### ISSUE TITLE
New Universal Login and wrong username/password closes Window

### ISSUE THREAD

**Issue by natelaff** [auth0/auth0-oidc-client-net#128]
Reopening #79 

When using the New Universal Login, if in the winforms client you type in the wrong username/password, the browser just closes and gives you an Http error. In the old flow, the browser would remain open during failed attempts.

You showed a screenshot, but you were not using the NEW Universal Login option, which is why you couldn't reproduce.

**Comment by damieng** [comment]
You don't need to create a whole new issue, we can open the original to keep the thread going.  Will carry on in #79.
