### ISSUE TITLE
Android.Util.AndroidRuntimeException under Android 6.0(Xamarin)

### ISSUE THREAD

**Issue by bojan96** [auth0/auth0-oidc-client-net#13]
Recently we migrated app to V2, but we have problem with Auth0 library under Android 6.0
Authentication works fine under Android 7.0, but on Android 6.0 we get Android.Util.AndroidRuntimeException when calling LoginAsync method of Auth0Client class.
Message is: 

> Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?

**Comment by ralph819** [comment]
I copy the PlatformWebView from this repo https://github.com/auth0/auth0-oidc-client-net/blob/master/src/Auth0.OidcClient.Android/PlatformWebView.cs

And add:
intent.AddFlags(ActivityFlags.NoHistory).AddFlags(ActivityFlags.NewTask);

**Comment by MalmoIt** [comment]
@ralph819 Did you use a renderer or did you copy the whole repo and made the Dlls yourself?

**Comment by ralph819** [comment]
I use a renderer, but I copy the same renderer PlatformerWebView from your
repo.

And replace it like this:

myAuth0ClientOptions.Browser = new MyPlatformWebView();

You only need to add a new Flag (ActivityFlags.NewTask) on the intent on
line 54 of
https://github.com/auth0/auth0-oidc-client-net/blob/master/src/Auth0.OidcClient.Android/PlatformWebView.cs

Example:
Replace this:
intent.AddFlags(ActivityFlags.NoHistory);
with this:
intent.AddFlags(ActivityFlags.NoHistory).AddFlags(ActivityFlags.NewTask);

I am testing it.

Mail send from my mobile, sorry for my bad English.
