### ISSUE TITLE
Slow response using RefreshTokenAsync and GetUserInfoAsync

### ISSUE THREAD

**Issue by OrihuelaConde** [auth0/auth0-oidc-client-net#141]
konrad.sopala from[ Auth0 Community](https://community.auth0.com/t/net-sdk-slow-response-using-refreshtokenasync-and-getuserinfoasync/37110) asked to me to create a new issue here.

> We are experiencing an slow response using the methods RefreshTokenAsync and GetUserInfoAsync. The refresh token takes up to 4.500ms and get user info up to 2.500ms. Our tenant is on a Free plan, is it normal to took too long?
> 
> Which SDK does this apply to?
> Auth0.OidcClient.Core / Auth0.OidcClient.WPF
> 
> Which verison of the SDK you are using?
> 3.1.2 / 3.1.3
> 
> Which version of the platform are you facing this error on?
> .Net Standard 2 / .Net Framework 4.7.2

**Comment by damieng** [comment]
I just ran a test using the [WPF test app checked into this repository](https://github.com/auth0/auth0-oidc-client-net/tree/master/test/WPF).

I added a stopwatch around the GetUserInfoAsync call:

```csharp
writeLine("Getting user info...");
var stopwatch = new Stopwatch();
stopwatch.Start();
var userInfoResult = await _auth0Client.GetUserInfoAsync(accessToken);
stopwatch.Stop();
Console.WriteLine($"{stopwatch.ElapsedMilliseconds}ms");
```
 
The call completed on my machine in 154ms.  I also added code to call RefreshTokenAsync and it completed in 253ms.

Could you try using the checked-in WPF test app above both with the built-in ClientID it uses and with your own to help try and narrow down the problem?

Also, can you let me know if you are using a proxy server in your environment?

**Comment by OrihuelaConde** [comment]
I've tried with my tenant and it give me 2026ms ([img](https://imgur.com/QTWpqtX)) on GetUserInfo, using "auth0-dotnet-integration-tests.auth0.com" as domain 2374ms.

Here is an [Speedtest ](https://www.speedtest.net/result/9008289401.png) of our connection, we are in Argentina, so the test is done to a NY Server, to be more accurate. We are not using any proxy.

**Comment by damieng** [comment]
Do you get similar performance using any of our other non-.NET SDKs?

**Comment by OrihuelaConde** [comment]
I don't know, we only use .Net. Could you guide me how to realize the test with other SDK?
