### ISSUE TITLE
Unable to save username on kindle Fire using Silk Browser or Chrome 

### ISSUE THREAD

**Issue by mcampbellbc83** [auth0/auth0-oidc-client-net#142]
We have an app that uses browser-based login. We set the browser to save userame, but the prompt is not provided when entering username/password.  You can download the app from the google play or Amazon app store - Clarigent MHSAFE.
![fire7login](https://user-images.githubusercontent.com/20644658/74608420-c8b41c80-50ae-11ea-9852-cff73597e990.png)

I have tested with other websites and the username prompt works as expected in the silk and chrome browser on kindle fire 7. Our app saves usernames properly on iphone and android phones.

Are there limitations on using browser-based login when saving usernames on kindle Fire 7 tablet?

When I attempt to login using this browser-based implementation, the modal pops up that looks like it is attempting to save the username when I begin to type password, but all this is displayed is a black key. Typically, it is an orange key with a prompt to save username.

![fire7loginusername](https://user-images.githubusercontent.com/20644658/74608436-f7ca8e00-50ae-11ea-99f2-db91d093d9bf.jpeg)

In the mobile apps, we used Auth0.OidcClient.iOS for iOS and Auth0.OidcClient.Android for Android. They’re open source libraries from Auth0 for integrating mobile apps with Auth0 - but basically implementations of the OIDC standard.

**Comment by damieng** [comment]
Hi.

We don't actually support or test Fire OS which Kindle devices use in this SDK. While they are based on Android they deviate in many subtle ways - the browser being one of them. I'm kind of surprised it works at all, to be honest, but I can provide a little more background information if that will be of help.

On Android, this SDK calls the "Chrome Custom Tab" with the login URL and then waits for that API to complete. Despite the name Chrome Custom Tabs can be implemented by any browser not just Chrome and I know Firefox also supports it and presumably based on your screenshot Amazon Silk too.

However, what these browsers do once we pass it the URL is entirely outside of the control of this SDK - which is what Chrome Custom Tabs is all about (if we can't interfere we can't break functionality when the browser upgrades nor can malicious apps intercept what's being entered).

I can only assume that Amazon Silk has an issue with saving passwords in Chrome Custom Tabs mode - it looks like Chrome itself used to as well based on https://bugs.chromium.org/p/chromium/issues/detail?id=676814

One thing you could try is using SystemBrowser on Fire OS and see if that then is happy to save passwords.

```csharp
var auth0Client = new Auth0Client {
  new Auth0ClientOptions {
    // rest of config options
    Browser = isFireOS ? (IBrowser) new SystemBrowser() : new ChromeCustomTabsBrowser()
  }
}
```

I'm not sure how you can reliably detect Fire OS though.

**Comment by damieng** [comment]
No further response. Will re-open if that changes.
