### ISSUE TITLE
Update Auth0.OidcClient to use AndroidX bindings

### ISSUE THREAD

**Issue by mduchev** [auth0/auth0-oidc-client-net#143]
### Describe the problem you'd like to have solved
Currently, if we try to use Auth0.OidcClient with Forms solution with Xamarin.Android project and we add Auth0.OidcClient.Android package to Android project, if we use Forms 4.5 and above, we will get an error. This error is since Forms 4.5 no longer use Android.Support libraries and instead it migrated to AndroidX ones.

### Describe the ideal solution
Ideally, the OidcClient package for Android will migrate also to AndroidX packages. This way, we won't have to install any of the legacy support packages.

## Alternatives and current work-arounds
Current workaround is to install Xamarin.Android.Support.CustomTabs package. This is not the ideal solution, since the support packages are no longer updated and this package also brings a lot of dependencies with it.

**Comment by mduchev** [comment]
Any ETA on this?

**Comment by beeradmoore** [comment]
Looks like there are two PRs for this. #146, and then #153, both by @damieng. does not look like it has had much movement unfortunately.

In our project this appears to be the only library holding us back to not having to use the migration packages anymore.

**Comment by Schmaga** [comment]
We are having the same issue while trying to migrate to the Auth0.OidcClient.AndroidX package. I had a look at the commit that was merged in #153, which adds the following two references to the AndroidX package:
```
<PackageReference Include="IdentityModel.OidcClient">
      <Version>3.1.2</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Browser">
      <Version>1.0.0</Version>
</PackageReference>
```

But if you have a look at the latest version of the Auth0.OidcClient.AndroidX on the official nuget server, those two depedencies are not listed in the latest package version, as can be seen here:
https://www.nuget.org/packages/Auth0.OidcClient.AndroidX/

Maybe no new version of the package was created after the merge of #153, or something went wrong while building the nuget?

Our current workaround was to integrate the complete Auth0.OidcClient.AndroidX project into our own solution. Then it works because dependencies are pulled correctly.

**Comment by damieng** [comment]
Sorry, it looks like somehow the nuget package didn't get updated with the dependencies.

**Comment by mduchev** [comment]
@Schmaga Yes, you can install the latest version of the second nuget package, but you'll still need to add the CustomTabs packages, which is not a solution at all. I still don't get why this takes that long and we still don't have any official release. :/

**Comment by damieng** [comment]
I just created a brand new regular Xamarin Android app (not Xamarin Forms) and added Auth0.OidcClient.AndroidX via Nuget then added a couple of lines to start the login process and it started fine with no additional errors.

Are you both using Xamarin Forms?

**Comment by damieng** [comment]
Additionall @Schmaga the IdentityModel.OidcClient is not needed as a dependency in Auth0.OidcClient.AndroidX or indeed any of the Auth0.OidcClient's except the .Core one which is a dependency of the others and so bring it in transitively. 

I was wondering whether the Xamarin.AndroidX.Browser was required but the test I just did showed that for a regular Android project using Auth0.OidcClient.AndroidX that dependency was not required - indeed Auth0.OidcClient.Android also does not specify Xamarin.Android.Support.CustomTabs and nobody has reported issues on that.

Xamarin Forms has never been supported by this library. While theoretically the iOS and AndroidX libraries would potentially work by adding each to the project-specific parts it is not clear how the state or protocol handler flow would be plumbed through the default Xamarin Forms template architecture.

**Comment by sstuenkel** [comment]
@damieng try this: [Android.zip](https://github.com/auth0/auth0-oidc-client-net/files/5180093/Android.zip) I just took the code from this repository and set Target Framework to Andorid 10. Also removed all project references and replaced them with the NuGet package reference to Auth0.OidcClient.AndroidX.

**Comment by damieng** [comment]
Thanks for that, I think I've found the problem and I have a fix.

**Comment by mduchev** [comment]
@damieng Yes, the issue happens on Forms. Here's another sample project - I've just created a new Xamarin.Forms solution and retargeted the Android SDKs to Android 10. As soon as I add the Auth0.OidcClient.AndroidX package, the solution won't build.
[TestAndroidXBindings.zip](https://github.com/auth0/auth0-oidc-client-net/files/5181898/TestAndroidXBindings.zip)

**Comment by SuperCorks** [comment]
Using `Auth0.OidcClient.AndroidX` worked for me. Thanks guys!
