### ISSUE TITLE
Update projects to build .NET Framework and .NET Core libraries

### ISSUE THREAD

**Issue by progdogusmc** [auth0/auth0-oidc-client-net#147]
### Describe the problem you'd like to have solved

I would like to be able to use these clients in .NET Core WinForms and WPF applications

### Describe the ideal solution

Convert the WinForms and WPF project files to the .NET Core format and add netcoreapp3.1 as a TargetFramework

## Alternatives and current work-arounds

Implement a custom version of the clients that rely on Auth0.OidcClient.Core in my .NET Core applications. Since Auth0.OidcClient.Core is .NET Standard 2.0 compliant, it can already be used in .NET Core applications without any issue.

### Additional context

None

**Comment by damieng** [comment]
Fixed in #149, thanks!
