### ISSUE TITLE
Is there any way to use oidc on Android & iOS without using deep links?

### ISSUE THREAD

**Issue by MAX-POLKOVNIK** [auth0/auth0-oidc-client-net#15]
I migrate to this oidc component from old Auth0 component. 
I don't really happy with new way of callback via deep links. 
I see PrepareLoginAsync and ProcessResponseAsync methods in IAuth0Client.
How can I use them with my own WebView[Controller/Activity] to authorize?
Can you provide example how to use them?

**Comment by MAX-POLKOVNIK** [comment]
@jerriep Thanks for fast reponse.

I use own IBrowser implementation to present custom login screen. On Android I use Fragment instead of Activity, and in iOS PushViewController instead of PresentViewController. 

Can I just add handler to WebView which will be listen url changes and when he see url starting with "com.mycompany.app://" pass this result to Auth0 oidc?

**Comment by jerriep** [comment]
Unfortunately I am not familiar with doing it that way as my experience with both iOS and Android is limited.

That being said, our Auth0 OIDC Client sits on top of https://github.com/IdentityModel/IdentityModel.OidcClient2, so you can perhaps look through their samples for an `IBrowser` implementation which suits you better and swap ours out for that:
https://github.com/IdentityModel/IdentityModel.OidcClient.Samples

I also just need to add that Auth0 does not recommend using an embedded browser, if that is the route you're thinking of going.  Please refer to [this blog post](https://auth0.com/blog/oauth-2-best-practices-for-native-apps/) for more information.

**Comment by MAX-POLKOVNIK** [comment]
I didn't any app that opens browser to authorize user. SDKs which provides OAuth authorization (like Facebook) opens internal WebView in their own screen implementation. Same do facebook if facebook app is not installed. 

Secondly most users don't like when app opens browser to log in. 

So I'll try make authorization with embedded WebView.
Thanks for your response.

**Comment by jerriep** [comment]
I understand your points. But it is definitely not best practice to use an embedded view anymore. The article I linked to above outlines why using an embedded browser is bad practice under the "User agents" section. Also, you need to be aware that identity providers such as Google will [block embedded browser requests](https://auth0.com/blog/google-blocks-oauth-requests-from-embedded-browsers/).

That being said, I can only advise you. It is up to you to decide whether you want to follow that advice. But from the Auth0 side this is not something we recommend customers do, and it is not something we will implement.
