### ISSUE TITLE
Support for PrefersEphemeralWebBrowserSession

### ISSUE THREAD

**Issue by mattjm** [auth0/auth0-oidc-client-net#157]
The library does currently support PrefersEphemeralWebBrowserSession on iOS.  It looks like the property is available in Xamarin:

https://docs.microsoft.com/en-us/xamarin/ios/release-notes/api-changes/ios-12-14-0-12-99-0

We recently added support for this to Auth0.Swift--seems like it could be useful here as well.

**Comment by frederikprijck** [comment]
Thanks for raising this @mattjm and sorry for the lack of response.
We will discuss this in our team and see how we prioritise this.
