### ISSUE TITLE
[Xamarin iOS] Second login of a user fails after logging out of the application

### ISSUE THREAD

**Issue by bacheric** [auth0/auth0-oidc-client-net#16]
We are trying to allow users to log out from our application and then log in again. The first login works just fine, but unfortunately the second login always fails with LoginResult containing the "invalid_state" error. There doesn't seem to be a general problem with the implementation as the issue constanly only affects the second login.
 
Is there something we have to "reset" before calling LoginAsync a second time? Very similar code on Android works just fine, the issue only occurs on iOS.
 
This is our implementation - as we are using Xamarin.Forms we are calling the native Auth0 client code within a dependency service. Otherwise, we are following the Xamarin quickstart guide.

```
class Auth0LoginManager : ILoginManager
{
    public static Auth0Client client = new Auth0Client(new Auth0ClientOptions
    {
        Domain = //redacted
        ClientId = //redacted
        Scope = "openid offline_access profile",
        LoadProfile = true,
    });
 
    public async Task GetUser()
    {      
        var loginResult = await client.LoginAsync(new { audience = "redacted"});
        if (!loginResult.IsError)
        {
            //Transfer auth result to PCL
        }
    }
}
```

**Comment by jerriep** [comment]
@ParticularEric I cannot seem to reproduce this. Does the Auth0 logs tell you anything?

**Comment by damieng** [comment]
No response from customer.
