### ISSUE TITLE
Feature Request: Add the ability to open Auth0 login in an embedded WebView

### ISSUE THREAD

**Issue by Schmaga** [auth0/auth0-oidc-client-net#162]
### Describe the problem you'd like to have solved

We have integrated Auth0 into a few of our Xamarin.Forms Applications using your Auth0.OidcClient.AndroidX package. Our current problem is that every time we call LoginAsync, it opens a new external browser window on the mobile device of the user. This leaves the app and makes it impossible to test the flow automated tools like Xamarin Test Cloud. And most importantly, it breaks the user experience if the user sees that he or she is leaving the app. This always leaves a weird impression with many users.

### Describe the ideal solution

An ideal solution would be the ability to use an existing embedded WebView. The MSAL library that Microsoft provides to authenticate using Azure AD allows this via the _WithUseEmbeddedWebView_ method.
[https://docs.microsoft.com/de-de/azure/active-directory/develop/msal-net-web-browsers](https://docs.microsoft.com/de-de/azure/active-directory/develop/msal-net-web-browsers)

A similar Action would be great to have in the Auth0 Client Login method

**Comment by frederikprijck** [comment]
Thanks for the request,

We have no intention to support Embedded WebView, one of the reasons is that Google has blocked OAuth flows from Embedded WebViews since 2017, see https://auth0.com/blog/google-blocks-oauth-requests-from-embedded-browsers/ for more information around this.

Even though this is not Xamarin, but the native WebView documentation also recommends using browsers such as Chrome: https://developer.android.com/reference/android/webkit/WebView

Our general recommendation is to use a trusted browser to ensure users are aware they are entering their credentials in a known and secure browser.

**Comment by Schmaga** [comment]
Thanks for reopening and inquiring. I might have been a bit too narrow with the original problem descrption. As far as I know, the main problem was not just Android, but especially die dialogue on iOS that asks the user every time if it is allowed to login using an external provider. Is there any way we can circumvent that and give a more seamless experience?

I will also ask my colleague again for more details and then come back to you with more info.

**Comment by frederikprijck** [comment]
There is more information around this here: https://community.auth0.com/t/ios-swift-remove-consent-dialog-social-login-with-auth0/9006/5

But in short, this is a decision from Apple to protect their users in case you want to authenticate using an external provider.

There is however a way to not show this popup, which is by using EphemeralSessions (there is a feature request for it here: https://github.com/auth0/auth0-oidc-client-net/issues/157).

Keep in kind that, even tho this removes the popup, it has other consequences for the user:

- No cookie is saved
- User has to re-login every time they click login
- Acts as if you are using an incognito browser

So if that popup is what you want to avoid, the only solution is to wait for https://github.com/auth0/auth0-oidc-client-net/issues/157 to be implemented. I will be closing this issue as a duplicate, but feel free to reopen if needed.
