### ISSUE TITLE
Xamarin Android - Parameter is required Parameter name: refresh_token

### ISSUE THREAD

**Issue by kgbuddhima** [auth0/auth0-oidc-client-net#164]
Please include the following information in your post:

* **Which SDK this is regarding:** Auth0.OdicClient.Android
* **SDK Version:** 3.13
* **Platform Version:** Xamarin 4.8.0.1269
* **Code Snippets/Error Messages/Supporting Details/Screenshots:** 

I was trying to call Parameter is required
Parameter name: RefreshTokenAsync() method from Xamarin Android app and I'm having following error "Parameter is required Parameter name: refresh_token"

here is my code

    private Auth0Client _auth0Client;
        
        public AuthenticationService()
        {
            _auth0Client = new Auth0Client(new Auth0ClientOptions
            {
               
                Domain = AuthenticationConfig.Domain,
                ClientId = AuthenticationConfig.ClientId,
                Scope = "openid profile email offline_access"
            },MainActivity.Instance);
        }

    public async Task<Auth0AccessTokenResponseModel> RefreshToken(string refreshToken)
        {
            Auth0AccessTokenResponseModel result = null;
            try
            {
                // TODO: check why these values come as null values
                RefreshTokenResult refreshTokenData = await _auth0Client.RefreshTokenAsync(refreshToken);
                if (refreshTokenData is RefreshTokenResult)
                {
                    result = new Auth0AccessTokenResponseModel()
                    {
                        AccessToken = refreshTokenData.AccessToken,
                        ExpiresIn = refreshTokenData.ExpiresIn,
                        IdToken = refreshTokenData.IdentityToken,
                        RefreshToken = refreshTokenData.RefreshToken
                    };
                }
            }
            catch (Exception ex)
            {

            }
            return result;
        }

And also I tried to pass the refresh token as an additional parameter , but it also behave like same

    await _auth0Client.RefreshTokenAsync(refreshToken, new { refresh_token = refreshToken });

**Comment by frederikprijck** [comment]
```
// TODO: check why these values come as null values
RefreshTokenResult refreshTokenData = await _auth0Client.RefreshTokenAsync(refreshToken);
```

Is the value of refreshToken null here?

**Comment by kgbuddhima** [comment]
> ```
> // TODO: check why these values come as null values
> RefreshTokenResult refreshTokenData = await _auth0Client.RefreshTokenAsync(refreshToken);
> ```
> 
> 
> Is the value of refreshToken null here?

no I pass a valid parameter as the refresh token.

**Comment by frederikprijck** [comment]
Can you verify it works if you use OidcClient (https://github.com/IdentityModel/IdentityModel.OidcClient) directly? we are not doing anything but passing that refreshToken to the OidcClient: https://github.com/auth0/auth0-oidc-client-net/blob/master/src/Auth0.OidcClient.Core/Auth0ClientBase.cs#L107

Would you be able to provide

**Comment by frederikprijck** [comment]
Closing this as there is no response.
Feel free to reply with more information and we can see to re-open.
