### ISSUE TITLE
Support to get the token from the authentication based proxy from native WPF application

### ISSUE THREAD

**Issue by fshabeer337** [auth0/auth0-oidc-client-net#165]
### Problem Description

> I am using the auth0.oidc.client.wpf for getting the token from the native WPF application.
But the environment where the native WPF application is installed is enabled with the authentication based proxy.
So we have the proxy URL with the username and password but there is no support from the **auth0.oidc.client.wpf** to fill in the proxy URL with the username and password.

### Ideal solution

> Expecting a solution where **auth0.oidc.client.wpf**  allows to fill in the proxy url with the username and password.
and we get the token as a result.

            _client = new Auth0Client(new Auth0ClientOptions
            {
                Domain = Settings.Default.Auth0Domain,
                ClientId = clientID,                
                Scope = "openid email offline_access",
               **_// Provision to pass the proxy url with the username and password details._**
            });

            _loginResult = await _client.LoginAsync();
            _token = _loginResult.IdentityToken;                
            refresh_token = _loginResult.RefreshToken; 

## Alternatives and current work-arounds

> As of now not able to figure out any workarounds for the native app.
Please suggest if there are any....

### Additional context
> I tired the solutions from the below links but nothing seems to be helpful
I provided the configs in the app.config file
https://stackoverflow.com/questions/186800/is-it-possible-to-specify-proxy-credentials-in-your-web-config

>Even to call something using the RestClient to provide the proxy details, there is no way in the **auth0.oidc.client.wpf**
var client = new RestClient("http://example.com")
client.Proxy = new WebProxy("http://proxy.example.com")
https://stackoverflow.com/questions/12051137/web-request-through-proxy-using-restsharp

**Comment by fshabeer337** [comment]
Found a workaround, by setting up the WebRequest.DefaultWebProxy to the application.
                    var proxyObject = new WebProxy("http://10.0.2.37:808/")
                    {
                        Credentials = new NetworkCredential("UserName", "Password");
                        // Or Credentials = CredentialCache.DefaultNetworkCredentials;
                    };

                    WebRequest.DefaultWebProxy = proxyObject;

**Comment by frederikprijck** [comment]
Great you found a workaround, closing this.
