### ISSUE TITLE
Incorrect warning message when trying to log out on iOS

### ISSUE THREAD

**Issue by mduchev** [auth0/auth0-oidc-client-net#166]
### Description
The warning message on iOS when we are logged-in and try to log out is incorrect. Instead of "do you want to sign out", it asks the same as if we are trying to log in - "do you want to sign in".

### Reproduction
Here's a sample project:
[DemoAuth0LogoutIssue.zip](https://github.com/auth0/auth0-oidc-client-net/files/5541026/DemoAuth0LogoutIssue.zip)

Steps to reproduce:
1) Open the solution;
2) Go to Auth0Service.cs file in the iOS project and adjust the 3 constants at the top - domain, clientId & scope;
3) Adjust also the bundle identifier & CFBundleURLSchemes to match your server configuration;
4) Run the project
5) Click on the login button, accept the system dialog and log in with valid credentials
6) If the login is successful, an alert dialog will be shown. After you close the dialog, click on the logout button.

Expected result:
The warning message in the dialog should be "XXXX wants to use "auth0.com" to Sign **OUT**"

Actual result:
The warning message in the dialog is the same as if we are trying to log in again - "XXXX wants to use "auth0.com" to Sign **IN**"
Here's a screenshot of the logout dialog:
<img width="273" alt="Screenshot 2020-11-14 at 17 51 14" src="https://user-images.githubusercontent.com/8217099/99151233-49d22b80-26a2-11eb-9eaf-942beb7e547c.png">

### Environment
This happens on iOS devices only since only there we have the warning system dialog.

**Comment by frederikprijck** [comment]
Hi,

This looks related to https://community.auth0.com/t/swift-login-alert-shows-up-when-you-logout/21598/22, even though that issue is being reported for our Swift SDK, I think the explanation about the issue is pretty much identical.

I will have a conversation internally to see if we can do something about this.

Keep in mind that the alert that is being shown is a system alert from Apple and we have no control over the text being shown.

**Comment by frederikprijck** [comment]
After some internal conversation, this is a result of how Apple handles situations such as how Auth0 handles logout. There is not much we can do at the SDK side of things.

We might open up a conversation internally with other teams to see if we can have an alternative way to logout for Native applications, however for now there is not much we can do about this.

Once we implement https://github.com/auth0/auth0-oidc-client-net/issues/157, this message will go away, both in case of signin and signout.

**Comment by mduchev** [comment]
Any timeline for the implementation?

**Comment by mduchev** [comment]
Thank you for the quick response. Is there any timeline for the implementation? I'm just asking since I see that this has been open for a couple of months now.

**Comment by frederikprijck** [comment]
I cant give any exact timeline. Keep in kind that any PR to address it is always welcome to speed things up.
