### ISSUE TITLE
Support net5.0

### ISSUE THREAD

**Issue by j2ghz** [auth0/auth0-oidc-client-net#167]
When trying to use `Auth0.OidcClient.WPF (3.1.7)` from a WPF project targeting `net5.0-windows`, the following build error appears:
| Severity | Code       | Description                                                                                                                                                                                                     | Project  | File                                                                                                 | Line | Suppression State | 
|----------|------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------|------------------------------------------------------------------------------------------------------|------|-------------------| 
| Error    | NETSDK1130 | Referencing a Windows Metadata component directly when targeting .NETCoreApp,Version=v5.0 is not supported. Use the C#/WinRT projection tool (https://aka.ms/cswinrt) or a provided projection for this target. | MainProject | C:\\Program Files\\dotnet\\sdk\\5.0.100\\Sdks\\Microsoft.NET.Sdk\\targets\\Microsoft.NET.Sdk.targets | 934  |                   | 

### Describe the ideal solution

Make the project compatibile with WPF projects targeting `net5.0-windows`.

## Alternatives and current work-arounds

Downgrade to `netcoreapp3.1`, or implement another authentication workflow yourself.

### Additional context

> Add any other context or screenshots about the feature request here.

**Comment by frederikprijck** [comment]
Hi,

Looking at https://github.com/dotnet/sdk/issues/13268, it looks like you should install the `Microsoft.Windows.CsWinRT NuGet package` Nuget package.

Would that help?

**Comment by j2ghz** [comment]
It didn't help.

I created a simple reproduction repo: https://github.com/j2ghz/Auth0WPF-167-repro/commits/master
I just created a .NET 5 WPF app using Visual Studio. Then I added Auth0.OidcClient.WPF and the build fails.

I tried Microsoft.Windows.CsWinRT in https://github.com/j2ghz/Auth0WPF-167-repro/pull/2, it didn't help.

What's wierd is that in the reproduction repo the error is not the same as my first post, it's now this:
| Severity | Code       | Description                                                                              | Project            | File                                                                                                                      | Line | Suppression State | 
|----------|------------|------------------------------------------------------------------------------------------|--------------------|---------------------------------------------------------------------------------------------------------------------------|------|-------------------| 
| Error    | NETSDK1135 | SupportedOSPlatformVersion 10.0.18362.0 cannot be higher than TargetPlatformVersion 7.0. | Auth0WPF-167-repro | C:\\Program Files\\dotnet\\sdk\\5.0.100\\Sdks\\Microsoft.NET.Sdk\\targets\\Microsoft.NET.TargetFrameworkInference.targets | 185  |                   |

**Comment by frederikprijck** [comment]
I am also looking into this. Looks like we are not the only ones experiencing this: https://github.com/dotnet/sdk/issues/14591
I am keeping an eye on that issue to see how it progresses.

Thanks.

**Comment by frederikprijck** [comment]
A little update on where things are at with .NET 5, currently in case of WPF:

I have a working example in .NET5 using the current SDK https://github.com/frederikprijck/auth0-oidc-wpf-net5. However, WebViewBrowser does not work and throws the following error:

> PlatformNotSupportedException: Operation is not supported on this platform. 

The example in .NET 5 is using `WebBrowserBrowser`, which is not recommended at all, as it is old and using IE.
So we are investigating recommended browser usage for .NET 5.

**Comment by frederikprijck** [comment]
Closing this as, technically, this SDK does support .NET5, it is only missing implementation for WebView2.
However, as this SDK allows you to provide your own browser instance, it should be usable with .NET 5 and WebView2 without changes to the SDK .

Having native WebView2 support in this SDK would be great, but not having that shouldn't stop you from using .NET 5.

Weview2 support is tracked through https://github.com/auth0/auth0-oidc-client-net/issues/169
