### ISSUE TITLE
Implement WebView2

### ISSUE THREAD

**Issue by natelaff** [auth0/auth0-oidc-client-net#169]
WebView2 is now GA: 
https://blogs.windows.com/msedgedev/2020/10/19/edge-webview2-general-availability/

I was unable to use the newer Edge based version of this library because it was unable to run in Elevated scenarios. I think this one resolves that as its not based on the UWP Edge

**Comment by frederikprijck** [comment]
Thanks for raising this.

This SDK allows for the consumers to create and provide their own custom browser implementations.

For example, in the case of WPF, to create a custom web browser you can:
- Create a class that inherits `IBrowser` the way is being done here: https://github.com/auth0/auth0-oidc-client-net/blob/master/src/Auth0.OidcClient.WPF/WebViewBrowser.cs
- Pass it as an option when creating an instance of `Auth0Client`: https://github.com/auth0/auth0-oidc-client-net/blob/master/src/Auth0.OidcClient.WPF/Auth0Client.cs#L16

Would this allow you to implement `WebView2`, or is there anything stopping you from doing so with the current SDK?

**Comment by natelaff** [comment]
Sure, I can do it myself, but it would also be something to just have default in the library :)

**Comment by frederikprijck** [comment]
> Sure, I can do it myself, but it would also be something to just have default in the library :)

We will have a look and see where it fits in our current priorities. Happy to take a PR if you are up for it tho.

**Comment by 1TheMuffinMan** [comment]
I agree with @frederikprijck 
Implementing this yourself is very easy. The hardest part is understanding how to do it.

For example:
1. Go to the Auth0.OidcClient.WPF project
2. Copy the class file `WebViewBrowser` into your own application and name it whatever you want.
3. Make sure you download the `Microsoft.Web.WebView2` nuget package.
4. In the IBrowser class add the async keyword to `InvokeAsync` method and update the following snippets:

            var window = _windowFactory();
            var webView = new WebView2();
            await webView.EnsureCoreWebView2Async();


            webView.NavigationStarting += (sender, e) =>
            {
                if (e.Uri.StartsWith(options.EndUrl))

            window.Show();
            webView.CoreWebView2.Navigate(options.StartUrl);

5. When you instantiate your Auth0Client specify your new IBrowser implementation in the configs `Browser` property.

**Comment by Waxime64** [comment]
.Net 5 have already WebBrower in framework without external librairy

**Comment by frederikprijck** [comment]
@Waxime64  what do you mean? WebView 2 is the defacto embedded browser available as of .NET 5, it is not an external library but it still needs to be wrapped in an `IBrowser` implementation in order to be used with this SDK.

**Comment by natelaff** [comment]
After finally doing this, it would be my advice that Auth0 not implement this, at least for a while. The browser itself works well, but there are too many extra considerations. The largest being you have to deploy and install the WebView2 Runtime with your app. I set my installer to do it, but ultimately I would see it being an unnecessary support issue on Auth0 end.

Once this is included with Windows then maybe this makes sense, but until that time I wouldn't bother including this in the library itself. It's easy enough to implement on your own.

**Comment by frederikprijck** [comment]
Hey @natelaff ,

Thanks for that feedback. I have looking into doing this myself as well and have a comparable conclusion.
I believe as an SDK we can not provide you with full WebView2 support without going down the rabbit hole you mentioned.

Most of the complexity will be with the consuming app to ensure the browser gets bundles, etc. At that moment, adding the custom Browsers might also just be something you implement yourself, for now.

Feel free to share your Browser implementation if you like tho, could be useful for future readers of this isse.

Also, we are holding of for .NET6 and MAUI and see how that will change things (if any, it might not change much for this SDK, we will see).

**Comment by Tonvengo** [comment]
Hey @frederikprijck 
Is it possible now to use auth0 in MAUI application? If yes, do you have any examples / documentation. I was trying to install Auth0.OidcClient.Android but is monoandroid is not suported in .NET6.

Let me know if this is the wrong place for a question. This was the only one place where you were mentioning .NET and MAUI :)
