### ISSUE TITLE
Should there be a method in the library for verifying a stored token?

### ISSUE THREAD

**Issue by 1TheMuffinMan** [auth0/auth0-oidc-client-net#172]
My specific use case is Xamarin Forms, but I imagine the following use case works for the other platforms as well. 

This library successfully logs a user in or out.

However, what is the standard workflow for checking if a user is logged in and whether the stored token is still valid?

For example, when a user opens the app you'd want to get the token from secure storage. If it exists, it should be decoded to confirm whether it's expired? Even so you're not sure if it's been revoked. Seems like there should be a method in the library `ValidateToken(...)` for instance to handle all of the corner cases.

If you do not like this idea can you explain the best practices for checking if the logged in user has a valid token or if I need to redirect them to login?

**Comment by frederikprijck** [comment]
Hi,

https://jwt.io/ lists some libraries that can be used for token verification in different frameworks. In case of .NET you could use Microsoft's `System.IdentityModel.Tokens.Jwt` https://www.nuget.org/packages/System.IdentityModel.Tokens.Jwt/ 

This is the same package as we are using to validate the token after a successful login and retrieval of the tokens. Our implementation can be found here https://github.com/auth0/auth0-oidc-client-net/blob/master/src/Auth0.OidcClient.Core/Tokens/IdTokenValidator.cs.

As this SDK is about integrating your application with Auth0, and not a library to validate JWT tokens we decided to not expose that functionality. There are plenty of libraries available that allow you to implement that.

Closing this, but feel free to continue the conversation if you have any difficulties with implementing any token validation.

**Comment by frederikprijck** [comment]
You can not revoke Access Tokens, more on this here https://community.auth0.com/t/best-practice-for-checking-if-token-is-revoked-in-api/17460/2.

If you are talking about Refresh Tokens, the Auth0 server will not allow sending revoked Refresh Tokens so you know it is revoked if it is not being accepted.

**Comment by 1TheMuffinMan** [comment]
@frederikprijck thank you for that link. Extremely detailed and well written.
