### ISSUE TITLE
webview2 runtime version

### ISSUE THREAD

**Issue by andreeasor** [auth0/auth0-oidc-client-net#176]
Using 1.0.721-prerelease requires according to the documentation minimum Microsoft Edge version 86.0.616.0. 
but when I use the current latest fixed x64 runtime  Version 87.0.664.75  (which is newer/higher) it throws the following exception:

Microsoft.Web.WebView2.Core.WebView2RuntimeNotFoundException: 'Couldn't find a compatible Webview2 Runtime installation to host WebViews.'

**Comment by frederikprijck** [comment]
We do not support WebView2 yet, see https://github.com/auth0/auth0-oidc-client-net/issues/169.
