### ISSUE TITLE
.Net 5 support

### ISSUE THREAD

**Issue by Waxime64** [auth0/auth0-oidc-client-net#183]
Add .Net 5 compatibility and with this framework you alreay have Browser in framework without any librairy. But you have to update Auth0 DLL

**Comment by frederikprijck** [comment]
Hey @Waxime64 ,

Could u elaborate on what u mean here ?

> with this framework you alreay have Browser in framework without any library

In order to support .NET 5, this SDK needs to support WebView2, which it doesn't yet. I am not sure what you mean with

**Comment by Waxime64** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.webbrowser?view=net-5.0
WebBroswer directly in .Net5 without external librairy

**Comment by frederikprijck** [comment]
This SDK already uses that browser for Winforms. If you want to use that, you should be able to do so with .NET5: https://github.com/auth0/auth0-oidc-client-net/blob/master/src/Auth0.OidcClient.WinForms/WebBrowserBrowser.cs

However, WebView2 is the recommended approach with .NET5, which we do not support yet.

Closing this as this SDK already supports WebBrowser.
