### ISSUE TITLE
Error loading discovery document - Windows 7 SP1

### ISSUE THREAD

**Issue by OrihuelaConde** [auth0/auth0-oidc-client-net#199]
### Describe the problem

After trying to login it get the error: "Error loading discovery document..."

`var loginResult = await _client.LoginAsync(extraParameters: extraParameters);`

### What was the expected behavior?

Open the universal login window.

### Reproduction

OS: Windows 7 SP1 with latest (not ESU) cumulative patch (KB4534310)

Try to login using code like this:

```
var extraParameters = new Dictionary<string, string>
            {
                { "audience", "https://some.thing" }
            };

var loginResult = await _client.LoginAsync(extraParameters: extraParameters);
```

![Auth0 TLS](https://user-images.githubusercontent.com/12591371/119221751-25c72b00-bac7-11eb-8c63-ded4b0c4c0c4.png)

### Environment

- **Version of this library used:** WPF 3.2.1
- **Which framework are you using, if applicable:** .NET Framework 4.7.2
- **Any other relevant information you think would be useful:** This was working well, it started to happens recently and only in Windows 7. Our tenant is using "Legacy TLS" to avoid any problem with our active clients until we check all of them can connect. As said before the OS with the issue is Windows 7 SP1 with latest (not ESU) cumulative patch (KB4534310) or fresh install. It is installed latest version of IE 11 and Edge for Windows 7.

**Comment by frederikprijck** [comment]
Hey,

Could you provide a bit more information? Like what browser are u using?
Ideally, it would be helpful if you could provide a reproduction sample for us to investigate.

Keep in kind that Windows 7 is out of support for a while now. https://support.microsoft.com/en-us/windows/windows-7-support-ended-on-january-14-2020-b75d4580-2cc7-895a-2c9c-1466d9a53962

**Comment by OrihuelaConde** [comment]
I'm sure that you can reproduce this issue in any Windows 7 PC with the WPF test code (https://github.com/auth0/auth0-oidc-client-net/tree/master/test/WPF). As I've mentioned I've installed the latest version of Internet Explorer 11 and Edge for Windows 7.
I know that Windows 7 is out of support, but we have customers that still using it. In our country more than 26% of the PC still use it, sadly.

Thanks.

**Comment by frederikprijck** [comment]
> I'm sure that you can reproduce this issue in any Windows 7 PC with the WPF test code

I have no access to a Windows 7 machine. Happy to look into a PR that resolves this for Windows 7 if this is really something you need.

> As I've mentioned I've installed the latest version of Internet Explorer 11 and Edge for Windows 7.

Sorry, I am asking what browser you are using with the SDK, which is not related to what browser is installed on the OS.

**Comment by OrihuelaConde** [comment]
I'm using the "default" Browser , like the code that I suggested to reproduce the issue. I'm testing in a VM with Hyper-V, It doesn't have installed any Dev tool to debug. The error that I'm showing is the one trow by the Exception of `LoginAsync`.
I'll try tomorrow to show the Exception itself instead of only the message, also the inner Exception (if any).

**Comment by OrihuelaConde** [comment]
I was doing some tests and the issue was how .Net Framework 4.7.2 handle TLS version selection. Prior to this version it uses the latest TLS version (hardcoded into the Framework), since 4.7 it uses the latest supported by the OS. In the particular case of Windows 7 it support TLS 1.1 and 1.2 applying a patch, but the Framework try to connect with the default version of the OS (1.0).
I catched the issue because the test app of WPF uses 4.6.1 and our app 4.7.2.
You can modify how the framework select the TLS version by editing the registry of Windows, but it means changing how the whole system handle it. To avoid that I edited my code to detect the latest version supported by the OS and switch to that version (`ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;`).
I'm going to close this issue, thanks.
