### ISSUE TITLE
Android browser is not closed after returning to the main app. (Xamarin.Droid)

### ISSUE THREAD

**Issue by Hiilbig** [auth0/auth0-oidc-client-net#202]
### Describe the problem
On Android the login browser is kept open in the background when the authentication window return control to the main application. If the customTabsIntent is called with the flags ActivityFlags.NoHistory and ActivityFlags.ClearTop, the browser will close itself. See [this](https://forums.xamarin.com/discussion/100286/xamarin-auth-android-chrome-custom-tabs-doesnt-close-on-redirect ) for further details.

### What was the expected behavior?
Android is able to close the browser window after login.

### Reproduction

- Step 1..
- Step 2..
- ...

### Environment

- **Version of this library used:** auth0.oidcclient.android 3.2.1
- **Which framework are you using, if applicable:** Xamarin Android 5.0.0
- **Other modules/plugins/libraries that might be involved:**
- **Any other relevant information you think would be useful:** I have a fix for the issue, but is unable to push a branch for review. Pushing a new branch and creating a pull request is not allowed apparently. What is the best way for me to push a possible solution?

**Comment by Hiilbig** [comment]
PR #203 has been suggested for this as a fix/enhancement.

**Comment by zinvob** [comment]
This is still a problem.
