### ISSUE TITLE
WinUI3 client and package plans?

### ISSUE THREAD

**Issue by jmiddour** [auth0/auth0-oidc-client-net#211]
Have you made plans to support WinUI3 in the future?

WinUI3/WindowsAppSdk 1.0 is supposed to support multiple application windows, which would mean that the current architecture of opening a new window to do the authentication would work with that release.

WinUI3/WindowsAppSdk 0.8 however, does not support multiple top level windows.  This would require some processing to make authentication work inside the main application window.  

For anyone else who may be interested, I have created an implementation (not necessarily what _should_ be the implementation) that would support auth0 workflow inside of the main application window.  You can find this code [here](https://github.com/jmiddour/auth0-oidc-client-net/tree/winui-client)

**Comment by frederikprijck** [comment]
No short-term plans, but happy to discuss this internally and see how we want to progress with WinUI3.

**Comment by frederikprijck** [comment]
Microsoft has a wide offering of platforms and we can't support all of them. Given the popularity of WinUI3, we currently have no plans. However, we can always reconsider when more people are looking for a solution for WinUI3.

Closing for now.
