### ISSUE TITLE
Allow Hybrid AuthenticationFlow and FormPost ResponseMode

### ISSUE THREAD

**Issue by TheXenocide** [auth0/auth0-oidc-client-net#22]
The underlying IdentityModel.OidcClient library supports (and defaults to) the Hybrid authentication flow, which allows a web server that is not the client application to process identification information and interact with the client. I understand why the Auth0 client defaults to using AuthenticationFlow.AccessCode and ResponseMode.Redirect, but in our case we would like the mobile client's browser session to be able to receive a cookie from the server to support Single Sign-On between native mobile applications and associated web applications simultaneously. 

Currently our application is implemented using some native components and some web based components and we would ideally tell the identity provider to pass the token to our web layer, which would set a cookie in the browser for the domain of the web application (which is separate from the identity provider) before redirecting to the application using the custom URI scheme, this way the application can shell to the browser for web application functionality and share the same authentication state as the mobile application. Additionally, the ResponseMode.Redirect does not support passing as much information between the identity provider and the web server, which is less essential for our purposes, but still helpful if the server is able to process the Post request, though it's worth noting that this is only useful for the Hybrid flow since the mobile application is unable to access form post data to its custom URI scheme.

Since these OidcClientOptions properties are not passed through via Auth0ClientOptions, the only way I currently see to override this behavior would be to use Reflection.

**Comment by damieng** [comment]
Hi.

This library is really just an opinionated wrapper over OidcClient that makes basic Auth0 scenarios easier across our platforms.

Alternative scenarios are usually better handled by calling the OidcClient directly using our code as a guide to any extra parameters you might want to pass and how to configure the remaining options.
