### ISSUE TITLE
Mention LaunchMode = LaunchMode.SingleTask Is Important in Xamarin.Forms, Xamarin.Android

### ISSUE THREAD

**Issue by AuriR** [auth0/auth0-oidc-client-net#221]
### Description

In the example code, it mentions how to set up the Android app. However, it doesn't point out how important the following line is to Auth0 processing the callback:

LaunchMode = LaunchMode.SingleTask

If that setting isn't pointed out as important, the browser never "returns" to the app after the callback. I found it easy to overlook the required change to the already-generated code. The text exacerbates this by discussing "register the intent" but doesn't mention "also ensure the app is launched in Single Task mode."

### Suggested Modification

In the Xamarin.Android Quick Start text, change:

_Register an intent which will handle this callback URL. An easy way to do this is to register the intent on the same activity from which you called the LoginAsync method to initiate the authentication flow._

to:

_First, modify the Activity Launch Mode to LaunchMode.SingleTask. This will ensure the callback returns the user to the running instance.

Then, register an intent which will handle this callback URL. An easy way to do this is to register the intent on the same activity from which you called the LoginAsync method to initiate the authentication flow._

### What was the expected behavior?

n/a

### Reproduction

n/a

**Comment by frederikprijck** [comment]
Hey @AuriR ,

Sorry for the delay here, got a couple of other things that had my attention internally, and this got lost from my radar.
Even tho the paragraph you copied is from our Quickstart, it's also important to mention that there is another paragraph that does explicitly call out this:

![image](https://user-images.githubusercontent.com/2146903/162711147-25ca463e-ae2c-40fa-9b1f-b016411d2c5e.png)

As we do call out the need to use `SingleTask` explicitly, I will close this issue.

**Comment by AuriR** [comment]
Thanks for the follow-up, Frederik. Much appreciated!

---
“Never confuse motion with action.” -Ben Franklin
Blog: https://auri.net – Twitter: @Auri
