### ISSUE TITLE
Add logging support to the client

### ISSUE THREAD

**Issue by duraz0rz** [auth0/auth0-oidc-client-net#223]
### Describe the problem you'd like to have solved
We're trying to troubleshoot some issues with a customer's SSO and network environment and noticed that we can't get any in-depth logs from the Auth0 client itself. We can pass in a web view and log certain events, but we have no way to trace through what the Auth0 client (and the underling OIDC client) is doing and how exactly it's failing.

### Describe the ideal solution
Right now, there's no way to log what's happening in a production environment. The Auth0 client has a bunch of `Debug.WriteLine` statements which are fine during local development, but there's nothing to help when the app is in production. It would be nice to be able to be able to trace through the Auth0 client via logs.

Also, the OIDC client supports logging via [Microsoft.Extensions.Logging]{https://docs.microsoft.com/en-us/dotnet/core/extensions/logging?tabs=command-line). A `LoggerFactory` instance is created when you create a new `OidcClientOptions` instance, which the client uses to get a logger to use. It would be nice to be able to get those logs, as well.

## Alternatives and current work-arounds
None, really. Hope that everything works in production all hunky dory!

**Comment by frederikprijck** [comment]
Hey @duraz0rz ,

I opened a PR to address this, can you please take a look and see if this would be what you had in mind and whether or not it allows you to achieve what you would want to achieve?

Thanks

**Comment by duraz0rz** [comment]
Yep, that looks like what I had in mind at the time. Unfortunately, I'm no longer at the company that was using this, so I can't get in and test it out.
