### ISSUE TITLE
Unsure as to Which DLLs to Redistribute for a WinForms Application

### ISSUE THREAD

**Issue by TRCarbone** [auth0/auth0-oidc-client-net#224]
I've added the Auth0.OidcClient.WinForms NuGet package to my WinForms application that targets .NET Framework 4.7

After building, my build output folder contains around 200 new DLLs. The obvious ones are:

Auth0.Oidc.Client.dll
Auth0.Oidc.Cliient.Core.dll
IdentityModel.dll
IdentityModel.OidcClient.dll

However, there are numerous DLLs that begin with "Microsoft." and "System." that have been added (i.e. System.Buffers.dll, Microsoft.Bcl.AsyncInterfaces.dll)

Is it necessary to redistribute all ~200 DLLs or am I missing something?

**Comment by frederikprijck** [comment]
Thanks for reaching out.

Could you elaborate on what you are asking? Typically, you would install the Nuget and use whatever comes with it. Our SDK doesn't do much on its own, but uses a couple of other dependencies, that all have their own set of dependencies.

Is there any particular problem you are facing?

**Comment by TRCarbone** [comment]
I guess you kind of answered the question. The dependencies appear to be what are adding all of the extra DLLs.

I decided not to use the package and wrote my own code for just the functions I required.
