### ISSUE TITLE
Browser closing too quickly to save password

### ISSUE THREAD

**Issue by elvenprogrammer** [auth0/auth0-oidc-client-net#225]
Hi everyone, I have users complaining they're not able to save passwords.
iOS users can see the dialog prompting to save, but it closes too quickly for them to tap.
Most of android users cannot even see the dialog. We somewhat were able to see it, so I guess it's just a timing issue.
Am I the only one experiencing this issue and there is something missing on my side (both on SDK or Auth0 configuration)?

**Comment by frederikprijck** [comment]
Hey,

Would you be able to provide some more information? Any chance something we can use to see the issue in action?
I am unaware of our SDK impacting anything regarding saving passwords, which is a browser/device thing.

Thanks

**Comment by elvenprogrammer** [comment]
![AppCantSavePassword](https://user-images.githubusercontent.com/48190349/171114215-b25f53a2-bd78-4fb0-91be-833e4641ed48.gif)

I'm attaching a gif of the process in case it is not clear, the issue is the browser closes immediately after a successful login, not allowing the browser to show the prompt to save password, The same happens for both iOS and Android.
I wonder I'm the only one experiencing this issue?

**Comment by frederikprijck** [comment]
It's expected for the browser to close as soon as you entered your credentials successfully. If you do not like that behavior, I assume you can implement your own Browser as per https://auth0.github.io/auth0-oidc-client-net/documentation/advanced-scenarios/browsers.html.

**Comment by elvenprogrammer** [comment]
In the end we created post login pages and redirected with actions https://auth0.com/docs/customize/actions/flows-and-triggers/login-flow/redirect-with-actions

Everything is working as expected in iOS, while in android when you save the password the user flow is stopped and chrome requires another user action to go on, so we also needed to add a continue button just for android
