### ISSUE TITLE
Impossible to login anymore, any recent breaking change ? 

### ISSUE THREAD

**Issue by ClementCHA** [auth0/auth0-oidc-client-net#232]
### Description

Any recent breaking change  ? Impossible to login anymore since a week now. 

### Expected behaviour

Authentification success

### Actual behaviour 

When use for the first time, the authentification window is opening successfully. If we create new user or even try to connect with existent username+ password => Authentification window is closing and it's impossible to connect. The window is briefly opening then immediatly closing. Important NOTE : We still can create new account. (screenShot 1)

### Steps to reproduce the problem

1) Launch the project for the first time 
2) authentification or inscription 
3) Fill the different text field 
4) Create/Login button
5) Window is closing
6) Click again on "Create/Login" 
7) the window is opening then immediatly closing 
8) Impossible to connect or to create new user again

### Language / Framework Versions

** UWP project C# ** 

### Testing environment

1. **Windows 11 Pro**

### Screenshots

![Auth Success HIde](https://user-images.githubusercontent.com/73785703/193548955-ecdcf0da-2c70-4669-b88b-506d7781b394.png)
![Elow Playground Hide](https://user-images.githubusercontent.com/73785703/193548957-71763e2d-7c5e-4808-a495-580b54d98240.png)

**Comment by ClementCHA** [comment]
Hello, thanks for your quick answer. 

I know that sounds cliché but we didn't made any change since at least 6 months on the application which is implementing Auth0 client. We didn't, our client didn't neither. 

We were indeed not on the latest version so we already try to update :  

`Auth0.ManagementApi 7.12 => 7.17.2`
`Auth0.OidcClient.UWP 3.2.4 => 3.2.5`

But that unfortunatly doesn't fix the problem yet.

(Sorry for the issues open twice on two different place 😬)

**Comment by frederikprijck** [comment]
If you haven't upgraded our SDK, or even haven't made any change to our SDK I can't realy tell what is causing this. 

I would recommend troubleshouting things on your side, such as devices, OS versions etc, to try and identify at what point it stopped working.

**Comment by ClementCHA** [comment]
I tried to update the SDK on your Sample and it's not working neither.

**Comment by ClementCHA** [comment]
**Important UPDATE** I just try to create a new blank app, install the latest SDK, follow the doc' and the problem is still there tho. 
Either in my brand new app or on in your Sample, that's aint working. Could you check on your side ? 

Sorry for the inconvenient and thanks !

**Comment by ClementCHA** [comment]
Do we need to add Domain in  Content URIs section of manifest ? 
![image](https://user-images.githubusercontent.com/73785703/193764997-87eceb4b-642e-4680-b5e9-37353704770c.png)

**Comment by frederikprijck** [comment]
Hey,

You should not need a `client_secret`. If you do, your Auth0 application might be configured incorrectly.

The code you refer to has been there for over 3 years now, so if it used to work before, the issue is not with that.

I would advice having a look into your Auth0 logs, which you can find on your Auth0 dashboard on manage.auth0.com, under Monitoring > Logs. 

Also be sure the application has Token EndPoint Authentication Method set to `None`:

![image](https://user-images.githubusercontent.com/2146903/193793043-1dbeb007-b396-4b2e-a62d-f06a7ceee872.png)

**Comment by ClementCHA** [comment]
Hello again (that's the last message, I swear) ! 

We finally find out, the probelm come from an Action we set in the application flow and that's aint about Auth0 (Yeah, we deserved that "_I told you so since two days now_") 

Please accept our apologies and thanks a lot for your time, your reaction time and your advices (And you're calm 😬 )

Thanks again and see you around ✌️
