### ISSUE TITLE
Bug when System.IdentityModel.Tokens.Jwt is installed

### ISSUE THREAD

**Issue by ChrisAllisonMalta** [auth0/auth0-oidc-client-net#26]
I'm using Xamarin.Forms, as per [this blog](https://auth0.com/blog/developing-mobile-apps-with-xamarin-forms-and-azure-functions/) it works fine but when I try and use the above library it updates some of the base packages which must break the auth0 library. 

Basically I authenticate fine as per the logs in the portal but I get a null token, pretty similar to [this](https://community.auth0.com/t/using-auth0-oidcclient-ios-cannot-login-pass-wordlessly/16853) post in the community

**Comment by damieng** [comment]
Is this still an issue?
