### ISSUE TITLE
Error loading discovery document: Error connecting to https://yourDomain/.well-known/jwks.json

### ISSUE THREAD

**Issue by mohsinraza-10P** [auth0/auth0-oidc-client-net#268]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0-oidc-client-net#readme) and the [documentation](https://auth0.github.io/auth0-oidc-client-net/documentation/intro.html), and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-oidc-client-net/api/Auth0.OidcClient.html) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-oidc-client-net/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

We implemented a sample integration of Auth0 in Xamarin.Forms application via this [QuickStart](https://auth0.com/docs/quickstart/native/xamarin/01-login) guide provided in the documentation. We're currently encountering an exception (See StackTrace) which is only occurring when we build into release mode as the linking is enabled for it to reduce the size of the application. At the moment we've tried with Android platform into release mode and facing this issue. I'm attaching the StackTrace into a txt file along with the Nuget Package versions snippets we're currently utilizing in our project. 

**StackTrace:** 
[auth0-exception.txt](https://github.com/auth0/auth0-oidc-client-net/files/12183791/auth0-exception.txt)

**Linker Config**
[linker.config.txt](https://github.com/auth0/auth0-oidc-client-net/files/12183977/linker.config.txt)

**Note:** It works fine in Debug mode as linking is not enabled for Debug build.

**Expected Behavior:**
Login functionality should work fine on release and debug builds both.

<img width="257" alt="Screenshot 2023-07-27 at 5 58 33 PM" src="https://github.com/auth0/auth0-oidc-client-net/assets/97949976/c45e91a8-0086-4895-92bd-5c2fafb36aa0">
<img width="257" alt="Screenshot 2023-07-27 at 5 58 40 PM" src="https://github.com/auth0/auth0-oidc-client-net/assets/97949976/aa5c0bff-444c-4e6a-970a-1dda1a5d6f7f">
<img width="246" alt="Screenshot 2023-07-27 at 5 58 50 PM" src="https://github.com/auth0/auth0-oidc-client-net/assets/97949976/652902f1-5d82-440b-8ccc-158366f6e597">

### Reproduction

It can be easily reproducible by initiating login flow by this code `client.LoginAsync(options)`. 

### auth0-oidc-client-net version

3.4.1

### .NET version

.NET Standard 2.0

### Platform

Android

### Platform version(s)

Android: 13

**Comment by frederikprijck** [comment]
Did you configure your domain? As I can see the stacktrace mentions ` Error connecting to https://yourDomain/.well-known/jwks.json`, which does not contain your domain?

**Comment by mohsinraza-10P** [comment]
@frederikprijck Yes I've already configured the domain but I've intentionally kept a placeholder into the StackTrace since its confidential and I cannot disclose it. As I mentioned into the description its working as expected on DEBUG build but only causing issue on RELEASE build.

**Comment by frederikprijck** [comment]
Can you verify you can access the link ?

**Comment by mohsinraza-10P** [comment]
@frederikprijck Yes I can access the link. 

FYI only, I might get back to you further on this thread by Monday, 31 July so please do not close this one due to inactivity during this time. Thanks

**Comment by frederikprijck** [comment]
Can you please provide a reproduction based on our samples application for us to look into? That will make it easier to look into.

Based on the fact that it works in debug, and you can access the link yourself, I would think the linker is causing issues and it might not be caused to our SDK.

**Comment by mohsinraza-10P** [comment]
Hey @frederikprijck - I got a chance to look at the sample application's link mode for [Android](https://github.com/auth0-samples/auth0-xamarin-oidc-samples/blob/master/Quickstart/01-Login/Android/AndroidSample/AndroidSample.csproj) & [iOS](https://github.com/auth0-samples/auth0-xamarin-oidc-samples/blob/master/Quickstart/01-Login/iOS/iOSSample/iOSSample.csproj). Both have "SdkOnly" value instead "Full". I think it won't be reproducible on the sample application.

For my use case the link mode is set to Full i.e. Link All and I'm not able to figure it out which assembly I'm missing to include it [here](https://github.com/auth0/auth0-oidc-client-net/files/12183977/linker.config.txt) in the configuration.

**Comment by frederikprijck** [comment]
Closing this as I think there's not much we can do.
