### ISSUE TITLE
Specify the audience

### ISSUE THREAD

**Issue by JoeCooper** [auth0/auth0-oidc-client-net#3]
There's no interface to specify the audience. This is necessary to access APIs. Without an API there isn't really much point in logging into anything.

I guessed, correctly, that I can do something like so –

var extraOptions = new Dictionary<string, string>();
extraOptions["audience"] = "...";
var task = client.LoginAsync(extraOptions);

– and it works, but just remember this when documenting it.

**Comment by jerriep** [comment]
Thank you @JoeCooper 

Yes, this is indeed documented:
https://auth0.github.io/auth0-oidc-client-net/documentation/advanced-scenarios/api-authorization.html
