### ISSUE TITLE
Documentation: Readme documentation link is broken

### ISSUE THREAD

**Issue by Gio2k** [auth0/auth0-oidc-client-net#315]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0-oidc-client-net#readme) and the [documentation](https://auth0.github.io/auth0-oidc-client-net/documentation/intro.html), and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-oidc-client-net/api/Auth0.OidcClient.html) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-oidc-client-net/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

The README contains a link to documentation of the Auth0 OIDC Client:
https://auth0.github.io/auth0-oidc-client-net/api/Auth0.OidcClient.html
Clicking on the link shows a 404 not found page

### Reproduction

Click on the link to the documentation provided on the readme

### auth0-oidc-client-net version

n/a

### .NET version

n7a

### Platform

Windows

### Platform version(s)

n/a

**Comment by frederikprijck** [comment]
Thanks for reporting, this should be fixed now.
