### ISSUE TITLE
An option to open the Webview in full screen ( Maximized ) using Auth0.OidcClient.WPF

### ISSUE THREAD

**Issue by emadgit** [auth0/auth0-oidc-client-net#318]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0-oidc-client-net#readme) and the [documentation](https://auth0.github.io/auth0-oidc-client-net/documentation/intro.html), and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-oidc-client-net/api/Auth0.OidcClient.html) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-oidc-client-net/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Hi there, 

I'm trying to use Auth0.OidcClient.WPF to integrate authentication to a desktop app, after we call: 
 `await client.LoginAsync();`

it will open the auth0 login within a webview, but the webview screen size as you can see in the screenshot, open with some fixed size and user need to  re-position  and scroll ( Specially if there are social logins or enterprise connection is config for the application ) to see the whole universal login within this form. 

<img width="1589" alt="Screenshot 2024-01-05 at 11 28 47" src="https://github.com/auth0/auth0-oidc-client-net/assets/26277146/1ad83bdd-0b30-4eff-8f39-6f60604b5169">

### Describe the ideal solution

I was wondering if there's an option or config currently to use and make the webview to open as a fullscreen? and if it's not, what do you think to have it as a new feature? I guess this make the flow more user friendly.

**Comment by frederikprijck** [comment]
You can create an instance of the WebViewBrowder and pass it the corresponding options, or even a window factory: https://github.com/auth0/auth0-oidc-client-net/blob/master/src/Auth0.OidcClient.WPF/WebViewBrowser.cs#L23-L35

Even more so, u can implement your own browser entirly and hook it into the SDK.
