### ISSUE TITLE
What does  BrowserResultType.UserCancel indicates?

### ISSUE THREAD

**Issue by spalmcc** [auth0/auth0-oidc-client-net#319]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0-oidc-client-net#readme) and the [documentation](https://auth0.github.io/auth0-oidc-client-net/documentation/intro.html), and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-oidc-client-net/api/Auth0.OidcClient.html) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-oidc-client-net/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Trying to find "BrowserResultType.UserCancel" indicates?

### Reproduction

Just need information

### Additional context

Having some issues with integrating Auth0. Need to know what "BrowserResultType.UserCancel"indicates?

### auth0-oidc-client-net version

3.5.0

### .NET version

.NET6

### Platform

Windows

### Platform version(s)

.NET6

**Comment by frederikprijck** [comment]
We generally use `UserCancel` when the browser is closed before the async operation is completed, see: https://github.com/search?q=repo%3Aauth0%2Fauth0-oidc-client-net%20UserCancel&type=code

**Comment by spalmcc** [comment]
> We generally use `UserCancel` when the browser is closed before the async operation is completed, see: https://github.com/search?q=repo%3Aauth0%2Fauth0-oidc-client-net%20UserCancel&type=code

Hi, Browser is closed? I have a desktop application (windows forms). I was trying to log out. What you have mentioned is not clear to me. 

BrowserResultType browserResult;
if (client != null)
{
    browserResult = await client.LogoutAsync();
   // browserResult  = BrowserResultType.UserCancel (This is what I am getting)
}

**Comment by frederikprijck** [comment]
Yes, we use webview and open the browser to handle login and logout.

Can you provide a reproduction so i can look into this ?

**Comment by spalmcc** [comment]
> Yes, we use webview and open the browser to handle login and logout.
> 
> Can you provide a reproduction so i can look into this ?

I am using webview.
The following is the code for logging out:-

BrowserResultType browserResult;
if (client != null)
{
browserResult = await client.LogoutAsync();

}

When I checked the value in "browserResult" I see "BrowserResultType.UserCancel " which is not correct. It should be "BrowserResultType.Success".

So I am trying to understand what exactly is meant by "BrowserResultType.UserCancel " and what can cause this?

**Comment by frederikprijck** [comment]
I updated my comment above to link to the implementation: https://github.com/auth0/auth0-oidc-client-net/blob/master/src/Auth0.OidcClient.WinForms/WebViewBrowser.cs#L62-L66

As you can seem we use UserCancel in the following case:

```
 window.Closing += (sender, e) =>
{
    if (!tcs.Task.IsCompleted)
       tcs.SetResult(new BrowserResult { ResultType = BrowserResultType.UserCancel });
};
```

So as you can see, and as I said, we set UserCancel when the browser is closed before the async operation is completed.
If UserCancel is unexpected, I will need to have a reproduction to understand what's going on.

**Comment by spalmcc** [comment]
Seems I have  found the issue. I missed adding "WebViewBrowser.cs" and "WebViewBrowserChromium.cs" classes. I am chekcing the same now.

**Comment by spalmcc** [comment]
I understand the issue now. My form was closed and after that I was trying to login thats why I was getting that issue.

**Comment by spalmcc** [comment]
thanks alot for the clarificaiton and support.
