### ISSUE TITLE
SFAuthenticationSession is deprecated

### ISSUE THREAD

**Issue by nicosabena** [auth0/auth0-oidc-client-net#32]
The Xamarin iOS package uses `SFAuthenticationSession` for iOS 11+.  The class was deprecated (see https://developer.apple.com/documentation/safariservices/sfauthenticationsession) and we should use [ASWebAuthenticationSession](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession) instead.

**Comment by jsauve** [comment]
Added PR #43 for this.

**Comment by damieng** [comment]
Will track on #43
