### ISSUE TITLE
Allow environment override for WebView2 

### ISSUE THREAD

**Issue by TinaBasinger** [auth0/auth0-oidc-client-net#321]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0-oidc-client-net#readme) and the [documentation](https://auth0.github.io/auth0-oidc-client-net/documentation/intro.html), and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-oidc-client-net/api/Auth0.OidcClient.html) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-oidc-client-net/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

We are using your Auth0.OidcClient.Winforms package in a program that we are installing to the Program Files folder.  By default, the WebView2 control will create a folder beside the calling application.  This does not work well in the Program Files folder due to permissions.  To work around this, the WebView2 object needs created with an environment set for the user's AppData folder.

### Describe the ideal solution

The WebViewBrowser class should have an optional way to provide a WebView2 environment.

### Alternatives and current workarounds

We have worked around this by creating a custom Browser class for the specific reason to add 2 lines of code.  Inside InvokeAsync, where your class creates the WebView2 object, we add these 2 additional lines:

CoreWebView2Environment cwv2Environment = await CoreWebView2Environment.CreateAsync(null, Application.LocalUserAppDataPath, null);
await webView.EnsureCoreWebView2Async(cwv2Environment);

This works, but it's terribly inefficient to create our own class for those 2 lines.  It also means that we'll miss out on future changes to the default WevViewBrowser that you provide.  As this use case seems like it would be a common scenario (installing and running from Program Files), it'd be helpful to many developers to provide some options around the WebView2 functionality.

**Comment by frederikprijck** [comment]
> This works, but it's terribly inefficient to create our own class for those 2 lines. It also means that we'll miss out on future changes to the default WevViewBrowser that you provide

We typically make very little changes to the Browsers. So I'd argue the implementation you have is fine and also what we recommend in situations like this.

> As this use case seems like it would be a common scenario

This is the first report of this, so not sure how common it is. Let's gather feedback and see if the need comes up.

Closing for now, as the recommendation is to roll your own browser implementation if ours does not work.

**Comment by GenieLabApp** [comment]
@TinaBasinger: I had the same problem. It can be solved by adding an environment variable:
``` 
Environment.SetEnvironmentVariable("WEBVIEW2_USER_DATA_FOLDER", @"C:\FolderForWebView2");
```
