### ISSUE TITLE
Vulnerabilities in the Auth0.OidcClient.Core assembly

### ISSUE THREAD

**Issue by DejanNZ** [auth0/auth0-oidc-client-net#328]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0-oidc-client-net#readme) and the [documentation](https://auth0.github.io/auth0-oidc-client-net/documentation/intro.html), and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-oidc-client-net/api/Auth0.OidcClient.html) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-oidc-client-net/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

We use the Auth0.OidcClient.WinForms NuGet package in our software.

Mend (WhiteSource) open source scans detected some transitive dependencies coming from the Auth0.OidcClient.Core assembly containing known medium vulnerabilities.

The affected packages are the last two in the list below:

Auth0.OidcClient.Core → Microsoft.IdentityModel.Protocols.OpenIdConnect (6.12.2) → System.IdentityModel.Tokens.Jwt (6.12.2) → Microsoft.IdentityModel.JsonWebTokens (6.12.2)

### Reproduction

Do Mend (WhiteSource) open source vulnerability scan for binaries that reference Auth0.OidcClient.WinForms.

### auth0-oidc-client-net version

3.2.8

### .NET version

4.8

### Platform

Windows

### Platform version(s)

10

**Comment by frederikprijck** [comment]
This should be fixed [here](https://github.com/auth0/auth0-oidc-client-net/pull/325). Please try our latest version of the SDK.

**Comment by DejanNZ** [comment]
Thanks for the prompt response.

**Comment by DejanNZ** [comment]
We found that the latest version of the Auth0.Oidc.Client.WinForms (4.0.0) still references the vulnerable version of System.IdentityModel,Tokens.Jwt (6.12.2). When we can expect an updated WinForms client Nuget? Thanks

![Auth0 dependencies](https://github.com/auth0/auth0-oidc-client-net/assets/18177860/cc89d29a-cd71-4432-8f18-e6990a843d1c)

**Comment by frederikprijck** [comment]
Sorry about that. The fix in `Auth0.OidcClient.Core` is released as `4.0.1`, it looks like installing the latest `Auth0.OidcClient.WinForms` (which is 4.0.0), still installs `Auth0.OidcClient.Core` 4.0.0.

Can you try updating (probably explicitly installing) Auth0.OidcClient.Core to 4.0.1 and see if it helps?

**Comment by DejanNZ** [comment]
That will work for now. Thanks
