### ISSUE TITLE
Problems with IdentityModel

### ISSUE THREAD

**Issue by hampoelz** [auth0/auth0-oidc-client-net#34]
Hey,
There are problems with the IdentityModel Packet v3.10.x

```
FileLoadException: Die Datei oder Assembly "IdentityModel, Version=3.7.0.0, Culture=neutral, PublicKeyToken=null" oder eine Abhängigkeit davon wurde nicht gefunden. Die gefundene Manifestdefinition der Assembly stimmt nicht mit dem Assemblyverweis überein. (Ausnahme von HRESULT: 0x80131040)
```

**Comment by damieng** [comment]
I am not able to reproduce this.  Do you have more information about your project you can share?

**Comment by hampoelz** [comment]
Sorry for the late reply - I've had a lot of stress in the last few days ...

When I call LoginAsync or LogoutAsync, I get such an error message. But only with IdentityModel Packet version 3.10.x
