### ISSUE TITLE
Unable to use if there is no discover document

### ISSUE THREAD

**Issue by sylvainonweb** [auth0/auth0-oidc-client-net#36]
### Description

The provider i try to use doesn't provide any discovery document.
Is it possible to use this library without discovery document and provider information programmatically?

### Prerequisites

- [X ] I have checked the [README documentation](https://github.com/auth0/auth0-oidc-client-net/blob/master/README.md).
- [ X] I have checked the [Auth0 Community](https://community.auth0.com/) for related posts.
- [ X] I have checked for related or duplicate [Issues](https://github.com/auth0/auth0-oidc-client-net/issues) and [PRs](https://github.com/auth0/auth0-oidc-client-net/pulls).
- [ X] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).
- [ X] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).
- [ X] I am reporting this to the correct repository.

### Environment

- Version of auth0-oidc-client-net being used : 2.3.1
- Version of the .NET Framework and what type of application (UWP, WinForms etc) : WPF .NET 4.5.2

### Reproduction
consistently reproducable

Please include:

![2019-03-01_11h55_04](https://user-images.githubusercontent.com/37140661/53634405-68686880-3c1a-11e9-92a6-faa9a36b1cef.png)

**Comment by sylvainonweb** [comment]
Nobody ?

**Comment by sylvainonweb** [comment]
7 days that I wait without an answer : don't think I will use this library.

**Comment by damieng** [comment]
This library is only intended for use with auth0.com and as such does not support features outside of what auth0.com offers.
