### ISSUE TITLE
No support for JsonWebSignatureAlgoritjm HS256

### ISSUE THREAD

**Issue by Valtarr** [auth0/auth0-oidc-client-net#4]
In Auth0 there is support for **JsonWebSignatureAlgoritjm** **HS256**.
And we are using that.
But there is currently no support for HS256 in OIDC client.
And we can not switch to another algorithm easily.
Please, add support for HS256 in OIDC client.

**Comment by jerriep** [comment]
Sorry, but this is not going to happen. HS256 requires a shared secret which can fairly easily be determined by decompiling the application.

Also, the underlying Auth0 infrastructure does not allow you to use HS256 with a Native Client.

Please see https://auth0.com/docs/api-auth/client-types for more information
