### ISSUE TITLE
What params does LogoutAsync() pass to the logout endpoint?

### ISSUE THREAD

**Issue by jsauve** [auth0/auth0-oidc-client-net#42]
I'm looking at this chunk of code:
https://github.com/auth0/auth0-oidc-client-net/blob/master/src/Auth0.OidcClient.Shared/Auth0Client.cs#L146-L166

What info does LogoutAsync() pass to the endpoint in order to logout the correct user? I see that the clientId is passed, and the logout URL, but I don't see where the individual user's id is passed so that the Auth0 backend knows which user session to end. I see that it DOES work, but I just don't understand HOW. On iOS, the SFWebAuthenticationSession (or ASWebAuthencationSession in iOS 12+) is an isolated browser with its own session and cookies. So when LogoutAsync() is called, the browser that appears to call the logout URL is presumably a fresh secure browser. How does it know which user to logout when it is called?

I'm asking because I'd really like to call the logout endpoint manually in code, not by popping a browser to the user. I understand the rationale for showing a browser when logging in, because the user is passing their credentials to the identity provider. However, if there are no credentials passed at logout, I would assume that logout should be achievable by calling the logout endpoint in code, in response to a button press or something. But I don't see how I can do that without passing the user's id token or something. But I can't find any docs on what those query params may be.

**Comment by beeradmoore** [comment]
Did you ever find an answer to this @jsauve ?

**Comment by damieng** [comment]
Each time you launch the secure browser from the app it retains its cookies from last time.  This is how it is able to re-login with the credentials and log out.
