### ISSUE TITLE
Password login via OIDC-conformant clients

### ISSUE THREAD

**Issue by tonyyyrocks39** [auth0/auth0-oidc-client-net#50]
We faced this issue sometimes. Not every time we login,That also if user has to input both user id and password.

Password login via OIDC-conformant clients with externally-hosted login pages is unsupported. Alternatively, login could have been initiated from the wrong place (e.g., a bookmark)

is there anything wrong here?
or just auth0 bug?

Also I have read some articles saying we have to set initiate_log_uri,How to do this in Xamarin.Android
thanks
thanks

**Comment by damieng** [comment]
I don't understand the issue here.  Can you list the steps involved in reproducing this issue?

**Comment by damieng** [comment]
No response.
