### ISSUE TITLE
Social login callback opens in default browser

### ISSUE THREAD

**Issue by natelaff** [auth0/auth0-oidc-client-net#54]
In Winforms, when you do a social login (Facebook) it opens a new tab in the system default browser to that callback with the OK result. A little ugly there. Is there a way to prevent this?

**Comment by natelaff** [comment]
Actually it only seems to do this with Facebook? Google, Microsoft, Twitter and Instagram do not exhibit this behavior.

**Comment by damieng** [comment]
Not able to reproduce this (screenshot attached) - I suspect perhaps the auth0 login page was forcing a new tab and perhaps that's been fixed there.

![image](https://user-images.githubusercontent.com/118951/67151495-c7e3b900-f27b-11e9-82cb-f92e3c93555d.png)

If you still have this problem respond here and I'll re-open the ticket.
