### ISSUE TITLE
How can I retrieve the user's claims while using a refresh token?

### ISSUE THREAD

**Issue by OrihuelaConde** [auth0/auth0-oidc-client-net#58]
### Description

How can I retrieve the user's claims while using a refresh token? 

`RefreshTokenResult result = await client.RefreshTokenAsync("abc");`

LoginResult has the user's claims but RefreshTokenResult doesn't.

### Environment

Please provide the following:

- Version of auth0-oidc-client-net being used:  Core and WPF 2.3.1
- Version of the .NET Framework and what type of application:  .Net Core 2.1 and .Net Framework 4.7.2 (WPF)

**Comment by damieng** [comment]
This library is a small wrapper around https://github.com/IdentityModel/IdentityModel.OidcClient2 which provides the functionality for performing the Login and Refresh etc.

I looked through the code and you're right - the RefreshToken path has no facility for providing the users claims :(  I don't think this is possible without changes upstream in OidcClient2.
