### ISSUE TITLE
Android.Util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag

### ISSUE THREAD

**Issue by rodrigojuarez** [auth0/auth0-oidc-client-net#78]
### Description

I'm trying to run the android sample app downloaded from the auth0 site for a xamarin.android and I got the following error:

_Android.Util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?_

### Prerequisites

- [*] I have checked the [README documentation](https://github.com/auth0/auth0-oidc-client-net/blob/master/README.md).
- [*] I have checked the [Auth0 Community](https://community.auth0.com/) for related posts.
- [*] I have checked for related or duplicate [Issues](https://github.com/auth0/auth0-oidc-client-net/issues) and [PRs](https://github.com/auth0/auth0-oidc-client-net/pulls).
- [*] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).
- [*] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).
- [*] I am reporting this to the correct repository.

### Environment

Please provide the following:

- Version of auth0-oidc-client-net being used: v2.4.0
- Version of the .NET Framework and what type of application (UWP, WinForms etc): Xamarin.Android

### Reproduction

- Download the sample xamarin app from the auth0 site after creating the app
- Run the app

**Comment by zinvob** [comment]
I tried implementing your solution inside my app, and I got the same error. Could you please help us out?

**Comment by zinvob** [comment]
I rolled back to version 2.3.1. Now it popped up with two choices of browser, I selected chrome and got to the login window. But when I was finished logging in with the correct information it returned to the app but gave me IsError as true with error "UserCancel".

**Comment by jennablackwell** [comment]
I'm getting this exception also on Android.

**Comment by danielPollackGitHub** [comment]
I am also having this issue. Please fix ASAP.

**Comment by dTveitan** [comment]
I'm also having this issue.

**Comment by danielPollackGitHub** [comment]
Any update on when this will get fixed? Our company is making a decision on whether or not to use Auth0.

**Comment by anandthirumala** [comment]
Could you please update on when this will get fixed? 

Same us the last person who commented, our company is also in the process of making a decision on whether or not to use Auth0 or some other providers we are looking at.

**Comment by damieng** [comment]
Can you try adding this to your `new Auth0ClientOptions` constructor as a temporary workaround:

```csharp
new Auth0ClientOptions() {
 ...
  Browser = new SystemBrowser();
}
```

**Comment by damieng** [comment]
I'd recommend either targeting SDK 8 or using our previous 2.3.1 release until we can get to the bottom of this.  (Currently investigating)

**Comment by damieng** [comment]
As a temporary workaround you can specify a SystemBrowser in your config options, e.g.

```csharp
_auth0Client = new Auth0Client(new Auth0ClientOptions {
   ...
    Browser = new SystemBrowser()
});
```

**Comment by damieng** [comment]
We have a PR up to fix this and we're just investigating what we can do about application switches while the browser is on-screen causing a cancellation.

**Comment by damieng** [comment]
Fix is now pushed to NuGet as 2.4.1 (Android package only.  Core and other packages are unchanged and still 2.4.0)

**Comment by dTveitan** [comment]
I'm not sure if others have the same problem, but now I have a new one.

I'm left in the webview while the "IsBusy" indicator is running, but it does not navigate back.
When I check my Auth0 User I can see that the "Latest Login" has been updated. Which in turn means that the authentication was successfull, but the code never returns with a login result.

The "ActivityMediator.Instance.Send(intent.DataString)" that should be triggered in OnNewIntent dosen't seem to be triggered. I don't know if this is the reason, but I thought it was worth mentioning.

**Comment by damieng** [comment]
I've just tried the new build on both Android 9 and 8 both using the test app from this repo with passing this and not passing this and all of them call back correctly with the signin flow.

The way it gets called back is via the returnUrl parameter it attempts to calculate based on your packageid so that the browser calls back in to your app on completion so there are three moving parts.

1. The packageId in your app (you have to set this)
2. The returnUrl that is calculated based on your packageId (we calculate this based on 1 but you can override/tweak it if it's not correct)
3. The calculated url needs to be configured for your client/application in the dashboard to whitelist it

Setting these up is part of the documentation in the Xamarin quickstart at https://auth0.com/docs/quickstart/native/xamarin/01-login

**Comment by dTveitan** [comment]
> I've just tried the new build on both Android 9 and 8 both using the test app from this repo with passing this and not passing this and all of them call back correctly with the signin flow.
> 
> The way it gets called back is via the returnUrl parameter it attempts to calculate based on your packageid so that the browser calls back in to your app on completion so there are three moving parts.
> 
> 1. The packageId in your app (you have to set this)
> 2. The returnUrl that is calculated based on your packageId (we calculate this based on 1 but you can override/tweak it if it's not correct)
> 3. The calculated url needs to be configured for your client/application in the dashboard to whitelist it
> 
> Setting these up is part of the documentation in the Xamarin quickstart at https://auth0.com/docs/quickstart/native/xamarin/01-login

My error (and my mistake) was an inconsistency with my callback uri and the "Package name" of my android app. Now it works like a charm! Thank you for the hint!

**Comment by damieng** [comment]
If there is an area of the docs you found confusing or something that would have made it a little clearer please let me know so we can improve them. 

Glad you're up and running.
