### ISSUE TITLE
New Universal Login and wrong username/password

### ISSUE THREAD

**Issue by natelaff** [auth0/auth0-oidc-client-net#79]
My guess is this isn't an issue with this client specifically, but the implementation of the new universal login, but just going to file here.

When using the New Universal Login, if in the winforms client you type in the wrong username/password, the browser just closes and gives you an Http error. In the old flow, the browser would remain open during failed attempts.

**Comment by damieng** [comment]
Not able to reproduce this (screenshot attached). If it is still a problem please respond here so I can reopen the issue.

![image](https://user-images.githubusercontent.com/118951/67151520-4b9da580-f27c-11e9-86b0-1eda5ff40070.png)

**Comment by natelaff** [comment]
You're not using the New Universal Login, that's the Classic login.

**Comment by damieng** [comment]
It was actually the New Universal Login with a custom theme but I just retested the WinForms in 3.1.0 with the default ULP theme and still can't reproduce.

![image](https://user-images.githubusercontent.com/118951/68988116-59950680-07e7-11ea-86b9-8b948285c98b.png)

Have you tried it with 3.x or above?  It now uses a totally different control on Windows that is Edge based not Internet Explorer based.

**Comment by natelaff** [comment]
Ah, 3.x seems to fix it. I was on 2.4.0

**Comment by damieng** [comment]
Yeah 2.x used Internet Explorer - nothing really worked that well with it any more :(  Even the GitHub.com sign-in page despite being owned by Microsoft took up about a third of the screen with a giant "Internet Explorer not supported" banner.

Feel free to respond here or raise a new issue if you have any problems with 3.x

**Comment by natelaff** [comment]
Actually I can reproduce this now. If you implement your own IBrowser the window will close with a 400 response.

Even if I use the exact code from https://github.com/auth0/auth0-oidc-client-net/blob/master/src/Auth0.OidcClient.WinForms/WebBrowserBrowser.cs

It will still do it.

Any idea on why that might be?

**Comment by natelaff** [comment]
Oh, wait. I see you what you did. You have that one and WebViewBrowser which is the new one. I plopped that in and everything is good again.

That's not going to be Win7 compatible though is it?

**Comment by natelaff** [comment]
Seems like you can "fix" this with the following:

                browser.NavigateError += (s, e) =>
                {
                    if (e.StatusCode != 400)
                    {
                        e.Cancel = true;
                        result.ResultType = BrowserResultType.HttpError;
                        result.Error = e.StatusCode.ToString();
                        signal.Release();
                    }
                };

Just ignoring a 400 Bad Request status code. I suppose this could mess up other things, but this does resolve the issue as far as I can tell.

**Comment by damieng** [comment]
The `WebViewBrowser` uses `WebViewCompatible` from the [Windows Toolkit](https://github.com/windows-toolkit/Microsoft.Toolkit.Win32) open source project.

From their description:

> Provides a version of WebView that is compatible with more OS versions. This control uses the Microsoft Edge rendering engine to show web content on Windows 10 version 1803 and later, and the Internet Explorer rendering engine to show web content on earlier versions of Windows 10, Windows 8.x, and Windows 7.

I'll checked out the `WebBrowserBrowser` tho - nothing in that class should have changed since the previous version where it was the default.

**Comment by natelaff** [comment]
Oh, it does work on 7 and 8? I found this and it said it was 10 only...
https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/wpf-winforms/webview

Nothing changed, this was always broken there but "fixed" in the latest version. It wasn't really fixed in the WebBrowserBrowser, you just changed the default implementation of IBrowser so this one wasn't used any longer.

**Comment by damieng** [comment]
That is the 'WebView' control - we use 'WebViewCompatible' that uses `WebView` if it can then falls back to IE if it can't.

**Comment by natelaff** [comment]
Ok, I'll switch to that thing since its compatible with 7. I suppose you can close (again, and for the last time hopefully 😂). Maybe this will help someone else who hasn't updated and has their own IBrowser implementation.

Thanks for your help and patience ;)

**Comment by damieng** [comment]
No problem.  I've been able to reproduce the closing-window on failed password with the older `WebBrowserBrowser` issue so that needs to be fixed.
