### ISSUE TITLE
can not work in Windows 7 with IE8, while work in Windows 10

### ISSUE THREAD

**Issue by yester** [auth0/auth0-oidc-client-net#8]
showing script error message box, auth0Lock is undefined.

**Comment by jerriep** [comment]
@yester Are you still experiencing it? Do you have any more details on this?

**Comment by yester** [comment]
After upgrading IE to version 11,  the error message has been gone. It seems the script engine compatibility issue.  Considering MS has stopped supporting to lower version IE, it should be okay.
