### ISSUE TITLE
Make ExtendedWebBrowser public for new IBrowser implementations

### ISSUE THREAD

**Issue by natelaff** [auth0/auth0-oidc-client-net#82]
I want to replace the IBrowser implementation, but ExtendedWebBrowser is internal, so I have to copy this code needlessly. Make this accessible please.

**Comment by natelaff** [comment]
Winforms

**Comment by damieng** [comment]
A primary goal of this library is to provide the best browser implementation (per platform) by default while letting people also plug in their own.

I think we want to avoid exposing internal implementation details as that runs counter to that goal.

In fact we have that very situation right now. A new Edge-compatible Browser integration is checked in to master and is the default.  It does not use ExtendedWebBrowser and I can easily imagine we remove ExtendedWebBrowser in the near future.
