### ISSUE TITLE
Targeting .Net Framework 4.6.1?

### ISSUE THREAD

**Issue by zabesto** [auth0/auth0-oidc-client-net#9]
Hello, I have a WinForms app that targets .Net Framework 4.6.1. With VS2017 I add the Nuget reference to this library and normal login works. However when I try to call RefreshTokenAsync I get a MissingMethodException at runtime. 

Should this package work with 4.6.1? Is there an alternative package I should be using? BTW, the Nuget install of the package seems to silently fail and I have to force the install from the console with "Install-Package Auth0.OidcClient.WinForms -Version 1.2.0" which worries me a bit.

**Comment by jerriep** [comment]
@zabesto Any updates on this?

**Comment by jerriep** [comment]
Closing this due to lack of information. Please feel free to re-open if you can provide more info
