### ISSUE TITLE
Login async not working after updating to xCode 11

### ISSUE THREAD

**Issue by nguyenminh92** [auth0/auth0-oidc-client-net#91]
Using this guide: https://auth0.com/docs/quickstart/native/xamarin#android

I was able to get auth0 implemented and working correctly on both android and iOS. A couple of days ago I decided to update to the latest of Xamarin forms to accommodate the new iOS 13. I updated Auth0.oidc.client to 2.4.2 as well.

Now client.LoginAsync() always return a LogInResult with error, with the description that says “UnknownError”. The app no longer prompt the Webview for user to log in like it did previously. No changes was made to domain or client id, and the code base is still working with the previous release of Xamarin forms and Auth0.oidc.client 2.4.0 (tested on another machine)

Also, this issue only happens on Xamarin forms iOS. Xamarin forms Android is still working correctly.

Has anyone run into this issue or something similar? Any insight would be greatly appreciated!

**Comment by damieng** [comment]
Are you setting option.RedirectUrl in your iOS app?  In 2.4.2 we fixed a bug where previously it wasn't honored.  If you had previously set it to an invalid value it might have worked because it was ignoring it and now it isn't.

**Comment by nguyenminh92** [comment]
Thanks @damieng. I was not setting it before, but following what you said i tried setting it to the right RedirectUri and still ran into the same issue.

**Comment by damieng** [comment]
Okay, we've figured out what is going on here. Xcode 11 introduces some breaking changes to ASWebAuthenticationSession which we adopted as the default in 2.3.1.

Immediate options until we can get a fix out:

- Use 2.3.1 of this library
- Modify your options to use the older pre-2.3.1 `SFSafariViewControllerBrowser`

The second option is probably the easiest, it would look like this:

```csharp
var myOptions = new Auth0ClientOptions {
  ...
  Browser = new SFSafariViewControllerBrowser();
}
```

**Comment by nguyenminh92** [comment]
Thanks @damieng. The second option works well! I really appreciate your quick responses!
