### ISSUE TITLE
Auth0 returned “UnknownError” on ios 13

### ISSUE THREAD

**Issue by Rews** [auth0/auth0-oidc-client-net#92]
I use Auth0.oidc.client 2.4.2 It works good for ios 12, but when i updated my xcode to "Version 11.0 (11A420a)" and compiled app for ios 13 client.LoginAsync() always return a LogInResult with error, with the description that says “UnknownError”.
Has anyone run into this issue or something similar?

**Comment by nguyenminh92** [comment]
Hey @Rews, I ran into the same issue and open an issue here: 
#91

**Comment by damieng** [comment]
Will track on #91 as it appears to be a duplicate issue.
